/**
 * report.js — PDF Report Generator
 *
 * Generates a professional PDF report of the cargo optimization run
 * using jsPDF (loaded via CDN in index.html).
 *
 * Depends on: window.jspdf.jsPDF (jsPDF CDN)
 * Called by:  App.generateReport() in app.js
 * No server / no install required — pure client-side.
 */

(function (global) {
  'use strict';

  /* ── THEME ── */
  const C = {
    navy:       [11,  15,  35],
    blue:       [37,  99,  235],
    blueLight:  [219, 234, 254],
    amber:      [180, 110,  10],
    amberLight: [254, 243, 199],
    green:      [21,  128,  61],
    greenLight: [220, 252, 231],
    red:        [185,  28,  28],
    redLight:   [254, 226, 226],
    slate:      [71,  85, 105],
    slateLight: [241, 245, 249],
    border:     [203, 213, 225],
    white:      [255, 255, 255],
    black:      [15,  23,  42],
    rowAlt:     [248, 250, 252],
  };

  /* hex color string from THREE.js int → [r,g,b] */
  function hexToRgb(hex) {
    const n = typeof hex === 'number' ? hex : parseInt(hex.replace('#',''), 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  }

  /* ── HELPERS ── */
  function setFill(doc, rgb)   { doc.setFillColor(...rgb); }
  function setDraw(doc, rgb)   { doc.setDrawColor(...rgb); }
  function setFont(doc, rgb)   { doc.setTextColor(...rgb); }
  function setSize(doc, s)     { doc.setFontSize(s); }
  function bold(doc)           { doc.setFont('helvetica', 'bold'); }
  function normal(doc)         { doc.setFont('helvetica', 'normal'); }
  function italic(doc)         { doc.setFont('helvetica', 'italic'); }

  /* draw a filled rounded rect */
  function fillRect(doc, x, y, w, h, rgb, r = 0) {
    setFill(doc, rgb);
    if (r > 0) doc.roundedRect(x, y, w, h, r, r, 'F');
    else        doc.rect(x, y, w, h, 'F');
  }

  /* draw a stroked rect */
  function strokeRect(doc, x, y, w, h, rgb, lw = 0.3) {
    setDraw(doc, rgb);
    doc.setLineWidth(lw);
    doc.rect(x, y, w, h, 'S');
  }

  /* text shorthand */
  function text(doc, str, x, y, opts = {}) {
    doc.text(String(str), x, y, opts);
  }

  /* horizontal line */
  function hline(doc, x, y, w, rgb, lw = 0.3) {
    setDraw(doc, rgb);
    doc.setLineWidth(lw);
    doc.line(x, y, x + w, y);
  }

  /* ── PAGE SETUP ── */
  const PW = 210, PH = 297; // A4 mm
  const ML = 14, MR = 14, MT = 14;
  const CW_PAGE = PW - ML - MR;

  /* ── NEW PAGE BOILERPLATE ── */
  function addHeader(doc, runId, pageNum) {
    // Top strip
    fillRect(doc, 0, 0, PW, 10, C.navy);
    setFont(doc, C.white); bold(doc); setSize(doc, 7);
    text(doc, 'CargoOpt3D  ·  Cargo Loading Optimization Report', ML, 6.8);
    normal(doc); setSize(doc, 6.5);
    text(doc, `Run ID: ${runId}`, PW - MR, 6.8, { align: 'right' });

    // Footer
    fillRect(doc, 0, PH - 8, PW, 8, C.slateLight);
    setFont(doc, C.slate); setSize(doc, 6);
    normal(doc);
    text(doc, 'Generated by CargoOpt3D — 3D Carton Loading & Container Space Optimization System', ML, PH - 3.2);
    text(doc, `Page ${pageNum}`, PW - MR, PH - 3.2, { align: 'right' });
  }

  /* ── SECTION HEADING ── */
  function sectionHead(doc, label, y) {
    fillRect(doc, ML, y, CW_PAGE, 7, C.blueLight, 2);
    setFont(doc, C.blue); bold(doc); setSize(doc, 9);
    text(doc, label, ML + 4, y + 5);
    normal(doc);
    return y + 10;
  }

  /* ── TWO-COLUMN KEY-VALUE TABLE ── */
  function kvTable(doc, rows, y, colW = [70, CW_PAGE - 70]) {
    const ROW_H = 7;
    rows.forEach((row, i) => {
      const bg = i % 2 === 0 ? C.white : C.rowAlt;
      fillRect(doc, ML, y, CW_PAGE, ROW_H, bg);
      strokeRect(doc, ML, y, CW_PAGE, ROW_H, C.border);

      setFont(doc, C.slate); normal(doc); setSize(doc, 8.5);
      text(doc, row[0], ML + 3, y + 5);

      setFont(doc, C.black); bold(doc);
      text(doc, row[1], ML + colW[0] + 3, y + 5);

      y += ROW_H;
    });
    normal(doc);
    return y + 2;
  }

  /* ── THREE-COLUMN TABLE WITH HEADER ── */
  function threeColTable(doc, headers, rows, y, colWidths) {
    const ROW_H = 6.5;
    const totalW = colWidths.reduce((a, b) => a + b, 0);

    // Header row
    fillRect(doc, ML, y, totalW, ROW_H, C.navy);
    setFont(doc, C.white); bold(doc); setSize(doc, 7.5);
    let cx = ML + 3;
    headers.forEach((h, i) => {
      text(doc, h, cx, y + 4.5);
      cx += colWidths[i];
    });
    y += ROW_H;

    // Data rows
    rows.forEach((row, ri) => {
      const bg = ri % 2 === 0 ? C.white : C.rowAlt;
      fillRect(doc, ML, y, totalW, ROW_H, bg);
      strokeRect(doc, ML, y, totalW, ROW_H, C.border, 0.2);

      cx = ML + 3;
      row.forEach((cell, ci) => {
        setFont(doc, ci === 0 ? C.black : C.slate);
        ci === 0 ? bold(doc) : normal(doc);
        setSize(doc, 7.5);
        text(doc, String(cell), cx, y + 4.5);
        cx += colWidths[ci];
      });
      y += ROW_H;
    });

    normal(doc);
    return y + 3;
  }

  /* ── HORIZONTAL BAR CHART ── */
  function barChart(doc, items, y) {
    // items: [{ label, value, max, color, unit }]
    const BAR_H = 7, GAP = 4, LABEL_W = 28, BAR_AREA = CW_PAGE - LABEL_W - 20;

    items.forEach(item => {
      const pct = Math.min(item.value / item.max, 1);

      // label
      setFont(doc, C.slate); normal(doc); setSize(doc, 8);
      text(doc, item.label, ML, y + 5.5);

      // track
      fillRect(doc, ML + LABEL_W, y + 1, BAR_AREA, BAR_H - 2, C.slateLight, 2);

      // fill
      if (pct > 0) {
        fillRect(doc, ML + LABEL_W, y + 1, BAR_AREA * pct, BAR_H - 2, item.color, 2);
      }

      // value label
      setFont(doc, C.black); bold(doc); setSize(doc, 7.5);
      text(doc, `${item.value.toFixed(1)}${item.unit}`, ML + LABEL_W + BAR_AREA + 3, y + 5.5);

      y += BAR_H + GAP;
    });

    normal(doc);
    return y + 2;
  }

  /* ── MINI PIE CHART (manual sectors) ── */
  function pieChart(doc, slices, cx, cy, r) {
    // slices: [{ label, value, color }]
    const total = slices.reduce((s, sl) => s + sl.value, 0);
    if (!total) return;
    let angle = -Math.PI / 2;

    slices.forEach(sl => {
      const sweep = (sl.value / total) * 2 * Math.PI;
      // jsPDF doesn't have pie primitives — draw using lines approximation
      // We'll fake it with a filled "wedge" using many tiny rectangles... 
      // Better: use doc.circle for single-slice, or just draw legend squares
      // For multi-slice we use the canvas approach via SVG path encoded as lines
      const steps = Math.max(6, Math.round(sweep / 0.15));
      const pts = [[cx, cy]];
      for (let i = 0; i <= steps; i++) {
        const a = angle + (sweep * i) / steps;
        pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
      }
      setFill(doc, sl.color);
      doc.setDrawColor(...sl.color);
      doc.lines(
        pts.slice(1).map((p, i) => [
          p[0] - (i === 0 ? cx : pts[i][0]),
          p[1] - (i === 0 ? cy : pts[i][1])
        ]),
        pts[0][0], pts[0][1],
        [1, 1], 'FD', true
      );
      angle += sweep;
    });

    // White circle in centre (donut effect)
    setFill(doc, C.white);
    doc.circle(cx, cy, r * 0.45, 'F');
  }

  /* ── UTILIZATION STATUS BADGE ── */
  function utilStatus(pct) {
    if (pct >= 80) return { label: 'Excellent', color: C.green,  bg: C.greenLight };
    if (pct >= 55) return { label: 'Good',      color: C.blue,   bg: C.blueLight  };
    if (pct >= 30) return { label: 'Moderate',  color: C.amber,  bg: C.amberLight };
    return              { label: 'Low',        color: C.red,    bg: C.redLight   };
  }

  function badge(doc, label, x, y, color, bg) {
    const w = doc.getTextWidth(label) + 6;
    fillRect(doc, x, y - 4, w, 5.5, bg, 1.5);
    setFont(doc, color); bold(doc); setSize(doc, 7);
    text(doc, label, x + 3, y);
    normal(doc);
    return x + w + 3;
  }

  /* ═══════════════════════════════════════════════
     MAIN EXPORT FUNCTION
  ═══════════════════════════════════════════════ */
  function generate(data) {
    /*
      data = {
        containerL, containerW, containerH,   // cm
        maxWeight,                             // kg
        placements,                            // [{ x,y,z,l,w,h, item:{ sku,wt,color } }]
        cartonTypes,                           // [{ sku,l,w,h,qty,wt,color }]
        totalWeight,
        runId,
        timestamp,
      }
    */
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

    const runId    = data.runId;
    const now      = data.timestamp;
    const cL_m     = (data.containerL / 100).toFixed(2);
    const cW_m     = (data.containerW / 100).toFixed(2);
    const cH_m     = (data.containerH / 100).toFixed(2);
    const cVol     = data.containerL * data.containerW * data.containerH / 1e6; // m³
    const pVol     = data.placements.reduce((s, p) => s + p.l * p.w * p.h / 1e6, 0);
    const spaceUtil = (pVol / cVol) * 100;
    const wtUtil    = (data.totalWeight / data.maxWeight) * 100;
    const placed    = data.placements.length;
    const requested = data.cartonTypes.reduce((s, t) => s + t.qty, 0);
    const unplaced  = requested - placed;

    /* ─── PAGE 1 ─── */
    let page = 1;
    addHeader(doc, runId, page);

    /* ── TITLE BLOCK ── */
    let y = 18;
    fillRect(doc, ML, y, CW_PAGE, 22, C.navy, 3);
    setFont(doc, C.white); bold(doc); setSize(doc, 16);
    text(doc, '3D Carton Loading Optimization Report', ML + CW_PAGE / 2, y + 9, { align: 'center' });
    setFont(doc, [147, 197, 253]); normal(doc); setSize(doc, 8);
    text(doc, `Generated: ${now}   ·   Run ID: ${runId}`, ML + CW_PAGE / 2, y + 16, { align: 'center' });
    y += 27;

    /* ── UTILIZATION SUMMARY CARDS ── */
    const cards = [
      { label: 'Space Utilization', value: spaceUtil.toFixed(1) + '%', ...utilStatus(spaceUtil) },
      { label: 'Weight Utilization', value: wtUtil.toFixed(1) + '%',   ...utilStatus(wtUtil)    },
      { label: 'Cartons Placed',  value: String(placed),  color: C.blue,  bg: C.blueLight  },
      { label: 'Unplaced',        value: String(unplaced), color: unplaced > 0 ? C.red : C.green, bg: unplaced > 0 ? C.redLight : C.greenLight },
    ];
    const cardW = (CW_PAGE - 9) / 4;
    cards.forEach((card, i) => {
      const cx = ML + i * (cardW + 3);
      fillRect(doc, cx, y, cardW, 20, card.bg, 3);
      // accent bar top
      fillRect(doc, cx, y, cardW, 2, card.color, 0);
      setFont(doc, card.color); bold(doc); setSize(doc, 14);
      text(doc, card.value, cx + cardW / 2, y + 11, { align: 'center' });
      setFont(doc, C.slate); normal(doc); setSize(doc, 7);
      text(doc, card.label, cx + cardW / 2, y + 17, { align: 'center' });
    });
    y += 26;

    /* ── CONTAINER SPECIFICATIONS ── */
    y = sectionHead(doc, '1. Container Specifications', y);
    y = kvTable(doc, [
      ['Length',          `${cL_m} m  (${data.containerL} cm)`],
      ['Width',           `${cW_m} m  (${data.containerW} cm)`],
      ['Height',          `${cH_m} m  (${data.containerH} cm)`],
      ['Weight Capacity', `${data.maxWeight.toLocaleString()} kg`],
      ['Total Volume',    `${cVol.toFixed(3)} m³`],
    ], y);

    /* ── UTILIZATION METRICS ── */
    y = sectionHead(doc, '2. Utilization Metrics', y);
    y = kvTable(doc, [
      ['Total cartons placed',  `${placed}`],
      ['Unplaced cartons',      `${unplaced}`],
      ['Total weight loaded',   `${data.totalWeight.toFixed(1)} kg`],
      ['Container volume used', `${pVol.toFixed(3)} m³`],
      ['Space utilization',     `${spaceUtil.toFixed(1)}%`],
      ['Weight utilization',    `${wtUtil.toFixed(1)}%`],
    ], y);

    /* ── UTILIZATION CHARTS ── */
    y = sectionHead(doc, '3. Utilization Charts', y);
    y = barChart(doc, [
      { label: 'Space',  value: spaceUtil, max: 100, color: spaceUtil > 80 ? C.green : spaceUtil > 55 ? C.blue : C.amber, unit: '%' },
      { label: 'Weight', value: wtUtil,    max: 100, color: wtUtil    > 80 ? C.red   : wtUtil    > 55 ? C.amber : C.green, unit: '%' },
      { label: 'Cartons placed', value: placed, max: requested, color: C.blue, unit: ` / ${requested}` },
    ], y);

    /* ── CARTON TYPE SUMMARY ── */
    y = sectionHead(doc, '4. Carton Type Summary', y);

    // Mini legend with colour swatches
    const typeCounts = {};
    data.placements.forEach(p => {
      typeCounts[p.item.sku] = (typeCounts[p.item.sku] || 0) + 1;
    });
    const typeRows = data.cartonTypes.map(t => {
      const rgb = hexToRgb(t.color);
      const placedCount = typeCounts[t.sku] || 0;
      return { t, rgb, placedCount };
    });

    // Swatch legend row
    const swatchSize = 4;
    typeRows.forEach((tr, i) => {
      const row = Math.floor(i / 3);
      const col = i % 3;
      const sx = ML + col * 60;
      const sy = y + row * 9;
      fillRect(doc, sx, sy, swatchSize, swatchSize, tr.rgb, 1);
      setFont(doc, C.black); normal(doc); setSize(doc, 7.5);
      text(doc, `${tr.t.sku}  ×${tr.placedCount} placed`, sx + swatchSize + 2, sy + 3.5);
    });
    y += Math.ceil(typeRows.length / 3) * 9 + 3;

    // Type table
    y = threeColTable(doc,
      ['SKU / Label', 'Dims (L×W×H cm)', 'Qty Req.', 'Placed', 'Wt/box kg', 'Total Wt kg'],
      data.cartonTypes.map(t => [
        t.sku,
        `${t.l}×${t.w}×${t.h}`,
        t.qty,
        typeCounts[t.sku] || 0,
        t.wt,
        ((typeCounts[t.sku] || 0) * t.wt).toFixed(1),
      ]),
      y,
      [38, 36, 18, 18, 22, 24]
    );

    /* ── PIE CHART ── */
    if (data.cartonTypes.length > 1) {
      const PIE_X = ML + CW_PAGE - 30, PIE_Y = y + 22, PIE_R = 18;
      const slices = data.cartonTypes.map(t => ({
        label: t.sku,
        value: typeCounts[t.sku] || 0,
        color: hexToRgb(t.color),
      })).filter(s => s.value > 0);

      if (slices.length) {
        // Label
        setFont(doc, C.slate); bold(doc); setSize(doc, 7.5);
        text(doc, 'Cartons by type', PIE_X, y + 3, { align: 'center' });
        pieChart(doc, slices, PIE_X, PIE_Y, PIE_R);

        // Legend next to pie
        let ly = y + 6;
        slices.forEach(sl => {
          const pct = (sl.value / placed * 100).toFixed(0);
          fillRect(doc, ML + CW_PAGE - 62, ly, 4, 4, sl.color, 1);
          setFont(doc, C.slate); normal(doc); setSize(doc, 7);
          text(doc, `${sl.label}: ${sl.value} (${pct}%)`, ML + CW_PAGE - 56, ly + 3.2);
          ly += 6;
        });
        y = Math.max(y + PIE_R * 2 + 10, ly + 4);
      }
    }

    /* ─── PAGE 2+: PLACEMENT COORDINATES ─── */
    doc.addPage();
    page++;
    addHeader(doc, runId, page);
    y = 18;

    y = sectionHead(doc, '5. Carton Placement Coordinates', y);

    // Note
    setFont(doc, C.slate); italic(doc); setSize(doc, 7.5);
    text(doc, 'Coordinates show the bottom-left-back corner (origin) of each placed carton. Units: cm.', ML, y);
    normal(doc);
    y += 5;

    const COL_W = [10, 30, 22, 18, 18, 18, 18, 18, 18, 12];
    const HEADERS = ['#', 'SKU', 'Size L×W×H', 'X', 'Y', 'Z', 'L', 'W', 'H', 'Wt kg'];
    const ROW_H = 6;
    const TOTAL_W = COL_W.reduce((a, b) => a + b, 0);
    const PAGE_BOTTOM = PH - 14;

    const drawTableHeader = (yy) => {
      fillRect(doc, ML, yy, TOTAL_W, ROW_H, C.navy);
      setFont(doc, C.white); bold(doc); setSize(doc, 7);
      let cx = ML + 2;
      HEADERS.forEach((h, i) => { text(doc, h, cx, yy + 4.2); cx += COL_W[i]; });
      return yy + ROW_H;
    };

    y = drawTableHeader(y);

    data.placements.forEach((p, ri) => {
      // Page break check
      if (y + ROW_H > PAGE_BOTTOM) {
        doc.addPage(); page++;
        addHeader(doc, runId, page);
        y = 18;
        y = sectionHead(doc, '5. Carton Placement Coordinates (continued)', y);
        y = drawTableHeader(y);
      }

      const bg = ri % 2 === 0 ? C.white : C.rowAlt;
      fillRect(doc, ML, y, TOTAL_W, ROW_H, bg);
      strokeRect(doc, ML, y, TOTAL_W, ROW_H, C.border, 0.15);

      // Color swatch in first col
      const rgb = hexToRgb(p.item.color);
      fillRect(doc, ML + 2, y + 1.5, 3, 3, rgb, 0.5);

      const cells = [
        ri + 1,
        p.item.sku,
        `${p.l}×${p.w}×${p.h}`,
        p.x.toFixed(1),
        p.y.toFixed(1),
        p.z.toFixed(1),
        p.l,
        p.w,
        p.h,
        p.item.wt,
      ];

      let cx = ML + 2;
      cells.forEach((cell, ci) => {
        if (ci === 0) { cx += COL_W[0]; return; } // skip # col (swatch drawn above)
        setFont(doc, ci <= 2 ? C.black : C.slate);
        ci <= 2 ? bold(doc) : normal(doc);
        setSize(doc, 7);
        text(doc, String(cell), cx, y + 4.2);
        cx += COL_W[ci];
      });

      // Re-draw # separately after swatch
      setFont(doc, C.slate); normal(doc); setSize(doc, 7);
      text(doc, String(ri + 1), ML + 6, y + 4.2);

      y += ROW_H;
    });

    y += 4;

    /* ── SUMMARY FOOTER ON LAST PAGE ── */
    if (y + 20 > PAGE_BOTTOM) {
      doc.addPage(); page++;
      addHeader(doc, runId, page);
      y = 18;
    }

    fillRect(doc, ML, y, CW_PAGE, 16, C.slateLight, 3);
    strokeRect(doc, ML, y, CW_PAGE, 16, C.border);
    setFont(doc, C.navy); bold(doc); setSize(doc, 9);
    text(doc, 'Optimization Summary', ML + 5, y + 6);
    setFont(doc, C.slate); normal(doc); setSize(doc, 8);
    text(doc,
      `${placed} of ${requested} cartons placed  ·  Space: ${spaceUtil.toFixed(1)}%  ·  Weight: ${data.totalWeight.toFixed(0)} kg / ${data.maxWeight.toLocaleString()} kg  ·  Volume: ${pVol.toFixed(3)} m³ / ${cVol.toFixed(3)} m³`,
      ML + 5, y + 13
    );

    /* ── SAVE ── */
    const filename = `CargoOpt3D_Report_${runId.slice(0, 8)}.pdf`;
    doc.save(filename);
  }

  global.ReportGen = { generate };

})(window);
