/**
 * report.js — FCOS PDF Report Generator v4.0
 * Changes from v3.1:
 *   - Report now contains ONLY visualisation pages: Overview → Stack 1..N (diagrams only)
 *   - Removed Loading Manifest and Loading Sequence pages entirely
 *   - Overview page: per-stack table (Stack #, Boxes in stack, Weight in stack, Avg weight/carton)
 *   - Stack pages: diagram only (no carton list table)
 */
'use strict';
(function () {

const C = {
  navy:   [15,  40,  80],
  amber:  [214, 130, 12],
  amberL: [255, 200, 80],
  text:   [20,  30,  50],
  muted:  [110, 125, 148],
  border: [210, 218, 230],
  surface:[245, 247, 250],
  white:  [255, 255, 255],
  success:[22,  163, 74],
  danger: [220, 38,  38],
};
const PW = 210, PH = 297, ML = 14, MR = 14, CW = PW - ML - MR;

const mmFmt  = v => `${Math.round(v)} mm`;
const pctFmt = v => `${(v * 100).toFixed(1)}%`;
const kgFmt  = v => `${Number(v).toFixed(1)} kg`;
const volFmt = v => `${(v / 1e9).toFixed(3)} m\u00b3`;

function hexToRgb(hex) {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return r ? [parseInt(r[1],16), parseInt(r[2],16), parseInt(r[3],16)] : [59,130,246];
}

/* ─── DEPTH-SLICE GROUPING ─────────────────────────────────────
 * Groups packed cartons that share the same depth position (X)
 * into one cross-sectional "wall" — exactly the highlighted block
 * shown in the 3D viewer (multiple rows/columns of boxes that sit
 * at the same depth, filled floor-to-ceiling, side-to-side, before
 * the pack advances toward the door). Each such group is treated
 * as ONE level in the report and rendered as a vertical, front-on
 * elevation grid — vertical stacking, exactly as highlighted.
 * ─────────────────────────────────────────────────────────── */
function computeStacks(packed) {
  const TOL = 40; // mm — depth-slice matching tolerance
  const stacks = [];
  for (const p of packed) {
    let s = stacks.find(s => Math.abs(s.x - p.x) < TOL);
    if (!s) { s = { x: p.x, items: [] }; stacks.push(s); }
    s.items.push(p);
  }
  // Within a slice: bottom → top (Y), then left → right (Z)
  for (const s of stacks) s.items.sort((a, b) => (a.y !== b.y ? a.y - b.y : a.z - b.z));
  // Back wall → door
  stacks.sort((a, b) => a.x - b.x);
  stacks.forEach((s, i) => { s.stackNumber = i + 1; });
  return stacks;
}

/* ─── PAGE CHROME ─────────────────────────────────────────── */
function pageHeader(doc, title, shipId) {
  doc.setFillColor(...C.navy);
  doc.rect(0, 0, PW, 20, 'F');
  doc.setFillColor(...C.amber);
  doc.rect(0, 0, PW, 2.5, 'F');
  doc.setFontSize(9.5); doc.setFont('helvetica','bold');
  doc.setTextColor(...C.amberL); doc.text('FCOS', ML, 13.5);
  doc.setFontSize(8); doc.setFont('helvetica','normal');
  doc.setTextColor(180,195,220); doc.text(`\u2014 ${title}`, ML+14, 13.5);
  doc.setFont('courier','normal'); doc.setFontSize(7);
  doc.setTextColor(160,175,200); doc.text(shipId||'', PW-MR, 13.5, {align:'right'});
}

function pageFooter(doc, shipment) {
  const pg = doc.internal.getCurrentPageInfo().pageNumber;
  doc.setFillColor(...C.surface);
  doc.setDrawColor(...C.border); doc.setLineWidth(0.3);
  doc.rect(0, PH-10, PW, 10, 'F');
  doc.line(0, PH-10, PW, PH-10);
  doc.setFontSize(6.5); doc.setFont('helvetica','normal');
  doc.setTextColor(...C.muted);
  doc.text('Generated by FCOS \u2014 Freight Container Optimization System', ML, PH-4);
  doc.text(`Page ${pg}`, PW-MR, PH-4, {align:'right'});
  if (shipment.customer && shipment.customer !== 'N/A')
    doc.text(`Customer: ${shipment.customer}`, PW/2, PH-4, {align:'center'});
}

function sectionBar(doc, num, label, y) {
  doc.setFillColor(...C.navy); doc.rect(ML, y, CW, 8, 'F');
  doc.setFillColor(...C.amber); doc.rect(ML, y, 2.5, 8, 'F');
  doc.setFontSize(7.5); doc.setFont('helvetica','bold');
  doc.setTextColor(...C.amberL); doc.text(String(num), ML+5.5, y+5.3);
  doc.setTextColor(...C.white); doc.text(label, ML+14, y+5.3);
  return y + 11;
}

/* ─── MAIN ────────────────────────────────────────────────── */
function generateReport(shipment, containerSpec, result, sequence) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({orientation:'portrait', unit:'mm', format:'a4'});

  // Gather cross-sectional stacks — each one = one visual page.
  const stacks = computeStacks(result.packed);

  // PAGE 1: Overview (stack count, boxes/weight/avg per stack — no shipment/manifest text)
  pageOverview(doc, shipment, containerSpec, result, stacks);

  // Per-stack pages — back wall → door (each = one cross-sectional wall, diagram only)
  for (const stack of stacks) {
    doc.addPage();
    pageHeader(doc, `STACK ${stack.stackNumber} \u2014 CARGO LAYOUT`, shipment.id);
    pageFooter(doc, shipment);
    pageStack(doc, stack, containerSpec, shipment);
  }

  doc.save(`FCOS_${shipment.id||'Report'}_${Date.now()}.pdf`);
}

/* ═══════════════════════════════════════════
   OVERVIEW PAGE (page 1) — stacks / boxes / weight / avg only
═══════════════════════════════════════════ */
function pageOverview(doc, shipment, spec, result, stacks) {
  // White background
  doc.setFillColor(255,255,255); doc.rect(0,0,PW,PH,'F');
  // Navy header
  doc.setFillColor(...C.navy); doc.rect(0,0,PW,40,'F');
  doc.setFillColor(...C.amber); doc.rect(0,0,PW,3,'F');
  doc.setFillColor(...C.amber); doc.rect(ML,7,3,26,'F');
  doc.setFontSize(24); doc.setFont('helvetica','bold');
  doc.setTextColor(...C.amberL); doc.text('FCOS', ML+9, 19);
  doc.setFontSize(8); doc.setFont('helvetica','normal');
  doc.setTextColor(180,195,215); doc.text('LOADING PLAN \u2014 STACK OVERVIEW', ML+9, 26);
  doc.setFontSize(7); doc.setFont('courier','normal');
  doc.setTextColor(170,190,220);
  const ts = new Date().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
  doc.text(`${shipment.id||'N/A'}  \u00b7  ${ts}`, ML+9, 32);

  let y = 48;

  // Top summary strip
  const totalBoxes  = result.packed.length;
  const totalWeight = result.totalWeight;
  const totalStacks = stacks.length;
  const avgPerStack = totalStacks ? totalBoxes / totalStacks : 0;

  const cw2 = (CW-9)/4, ch = 20;
  const summary = [
    {label:'Total Stacks',    value:String(totalStacks),       color:C.navy},
    {label:'Total Boxes',     value:String(totalBoxes),        color:C.navy},
    {label:'Total Weight',    value:kgFmt(totalWeight),        color:C.navy},
    {label:'Avg Boxes/Stack', value:avgPerStack.toFixed(1),    color:C.amber},
  ];
  for (let i=0;i<summary.length;i++) {
    const kx = ML + i*(cw2+3);
    doc.setFillColor(...C.surface); doc.setDrawColor(...C.border); doc.setLineWidth(0.3);
    doc.roundedRect(kx, y, cw2, ch, 2, 2, 'FD');
    doc.setFillColor(...summary[i].color); doc.roundedRect(kx, y, 2.5, ch, 1, 1, 'F');
    doc.setFontSize(14); doc.setFont('helvetica','bold');
    doc.setTextColor(...summary[i].color); doc.text(summary[i].value, kx+7, y+11.5);
    doc.setFontSize(6.3); doc.setFont('helvetica','normal');
    doc.setTextColor(...C.muted); doc.text(summary[i].label.toUpperCase(), kx+7, y+16.5);
  }
  y += ch + 10;

  // Per-stack table
  y = sectionBar(doc, '01', 'STACK-BY-STACK BREAKDOWN  (back wall \u2192 door)', y);

  const rows = stacks.map(s => {
    const items   = s.items;
    const wTotal  = items.reduce((sum,p)=>sum+p.weight, 0);
    const avgW    = items.length ? wTotal / items.length : 0;
    return ['', `Stack ${s.stackNumber}`, String(items.length), kgFmt(wTotal), kgFmt(avgW)];
  });

  doc.autoTable({
    startY: y,
    head: [['', 'Stack', 'Boxes in Stack', 'Weight in Stack', 'Avg Wt / Carton']],
    body: rows,
    margin: {left:ML, right:MR, top:23, bottom:14},
    headStyles:         {fillColor:C.navy, textColor:C.white, fontSize:8, fontStyle:'bold', cellPadding:3.2},
    bodyStyles:         {fillColor:[255,255,255], textColor:C.text, fontSize:8.5, cellPadding:3.4},
    alternateRowStyles: {fillColor:C.surface},
    columnStyles: {
      0:{cellWidth:8},
      1:{cellWidth:30, fontStyle:'bold', textColor:C.navy},
      2:{cellWidth:42},
      3:{cellWidth:46},
      4:{cellWidth:46},
    },
    theme: 'plain',
    willDrawCell: (data) => {
      if (data.section==='body' && data.column.index===0) {
        const s = stacks[data.row.index];
        const first = s && s.items[0];
        if (first) {
          doc.setFillColor(...hexToRgb(first.color||'#3B82F6'));
          doc.circle(data.cell.x+4, data.cell.y+data.cell.height/2, 1.8, 'F');
        }
      }
    },
    didDrawPage: () => {
      pageFooter(doc, shipment);
    },
  });
}

/* ═══════════════════════════════════════════
   STACK PAGE (cross-sectional wall = one level)
   Visualisation only — no carton list table.
═══════════════════════════════════════════ */
function pageStack(doc, stack, spec, shipment) {
  const stackNum = stack.stackNumber;
  const items    = stack.items; // bottom→top, left→right
  let y = 23;

  // Stack badge + stats
  doc.setFillColor(...C.navy); doc.roundedRect(ML, y, 38, 9, 2, 2, 'F');
  doc.setFontSize(9); doc.setFont('helvetica','bold');
  doc.setTextColor(...C.white); doc.text(`STACK  ${stackNum}`, ML+4, y+6.3);

  const sw   = items.reduce((s,p)=>s+p.weight, 0);
  const yMax = Math.max(...items.map(p=>p.y+p.h));
  const avgW = items.length ? sw / items.length : 0;
  doc.setFontSize(8); doc.setFont('helvetica','normal');
  doc.setTextColor(...C.text);
  doc.text(`${items.length} box${items.length!==1?'es':''}  \u00b7  ${sw.toFixed(1)} kg total  \u00b7  avg ${avgW.toFixed(1)} kg/box  \u00b7  up to ${Math.round(yMax)} mm tall`, ML+42, y+6.3);
  y += 13;

  // ── Caption banner — replaces faint floating text inside the diagram ──
  doc.setFillColor(...C.navy); doc.rect(ML, y, CW, 7, 'F');
  doc.setFillColor(...C.amber); doc.rect(ML, y, 2.5, 7, 'F');
  doc.setFontSize(7); doc.setFont('helvetica','bold');
  doc.setTextColor(...C.white);
  doc.text('FRONT ELEVATION', ML+6, y+4.7);
  doc.setFont('helvetica','normal'); doc.setTextColor(...C.amberL);
  doc.text('(looking from the door)', ML+34, y+4.7);
  doc.setFont('helvetica','bold'); doc.setTextColor(...C.white);
  doc.text(`Depth slice  X \u2248 ${Math.round(stack.x)} mm from back wall`, ML+CW-4, y+4.7, {align:'right'});
  y += 10;

  // ── Front-on elevation diagram — boxes stacked vertically AND
  //    side-by-side, exactly as one cross-sectional wall (the
  //    highlighted block) is built, floor-to-ceiling, wall-to-wall ──
  const diagW = CW;
  const diagH = PH - y - 16; // fill remaining page height since this is the only content
  const pad   = 6;

  doc.setFillColor(238,236,230);
  doc.setDrawColor(...C.border); doc.setLineWidth(0.4);
  doc.rect(ML, y, diagW, diagH, 'FD');

  const cH = spec.height, cWid = spec.width;
  const innerW = diagW - pad*2;
  const innerH = diagH - pad*2;
  const sx = innerW / cWid;   // Z → horizontal
  const sy = innerH / cH;     // Y → vertical (inverted: floor at bottom)

  const floorY = y + diagH - pad; // page-Y of the container floor

  const sorted = [...items].sort((a,b)=>(a.cartonNumber||0)-(b.cartonNumber||0));
  for (const p of sorted) {
    const rx = ML + pad + p.z * sx;
    const rh = Math.max(p.h * sy, 4);
    const ry = floorY - (p.y + p.h) * sy;          // top edge of the box
    const rw = Math.max(p.w * sx, 4);
    const rgb = hexToRgb(p.color || '#D9A66C');

    // Box body
    doc.setFillColor(...rgb);
    doc.setDrawColor(255,255,255); doc.setLineWidth(0.6);
    doc.rect(rx, ry, rw, rh, 'FD');
    doc.setDrawColor(0,0,0); doc.setLineWidth(0.2);
    doc.rect(rx, ry, rw, rh);

    // Carton number, centred
    const fs = Math.max(Math.min(rw*0.22, rh*0.3, 11), 4);
    doc.setFontSize(fs); doc.setFont('helvetica','bold');
    doc.setTextColor(255,255,255);
    doc.text(`#${p.cartonNumber||''}`, rx+rw/2, ry+rh/2+fs*0.1, {align:'center'});

    // SKU + size below number if there's room
    if (rh > 14 && rw > 12) {
      doc.setFontSize(Math.max(fs*0.5, 3.4));
      doc.setFont('helvetica','normal');
      const sk = (p.sku||'').length>9 ? p.sku.substring(0,8)+'\u2026' : p.sku;
      doc.text(sk, rx+rw/2, ry+rh/2+fs*0.1+fs*0.82, {align:'center'});
      doc.setFontSize(Math.max(fs*0.42, 3));
      doc.text(`${Math.round(p.weight)} kg`, rx+rw/2, ry+rh/2+fs*0.1+fs*1.5, {align:'center'});
    }
  }

  // Ground line
  doc.setDrawColor(...C.text); doc.setLineWidth(0.6);
  doc.line(ML+pad, floorY, ML+pad+innerW, floorY);

  // Axis labels — darker, higher-contrast against the diagram background
  doc.setFontSize(6.5); doc.setFont('helvetica','bold'); doc.setTextColor(...C.text);
  doc.text('\u25c4 LEFT WALL', ML+pad+1, y+diagH-1.5);
  doc.text('RIGHT WALL \u25ba', ML+pad+innerW-23, y+diagH-1.5);

  // Scale bar
  const barMm = 500, barPx = barMm*sx;
  const bx = ML+pad+4, by = floorY-4;
  doc.setDrawColor(...C.text); doc.setLineWidth(0.4);
  doc.line(bx, by, bx+barPx, by);
  doc.line(bx, by-1.5, bx, by+1.5);
  doc.line(bx+barPx, by-1.5, bx+barPx, by+1.5);
  doc.setFontSize(5.5); doc.setFont('helvetica','bold'); doc.setTextColor(...C.text);
  doc.text('500 mm', bx+barPx/2, by-2, {align:'center'});
}

window.FCOS_REPORT = { generateReport };
})();
